[project]
name = "payroll-example"
version = "0.2.1"
description = "Allows our company ACME Inc. to calculate the amount of money each employee is owed each month"
authors = [{ name = "Sam Hill", email = "s.hill@yorksj.ac.uk" }]
requires-python = ">=3.12,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[dependency-groups]
dev = ["pytest>=8.3.5,<9"]

[tool.uv]
default-groups = "all"

[tool.hatch.build.targets.sdist]
include = ["src/payroll_example"]

[tool.hatch.build.targets.wheel]
include = ["src/payroll_example"]

[tool.hatch.build.targets.wheel.sources]
"src/payroll_example" = "payroll_example"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = "src"
